self-hosted-runner:
  labels:
    - dev-local
    - production

config-variables:
  - DEPLOY_PATH_DEV
  - ENTRA_CLIENT_ID
  - ENTRA_TENANT_ID
  - IIS_SITE_NAME
  - IIS_SITE_NAME_DEV
  - LAYOUTPARSER_API_URL
  - LAYOUTPARSER_API_URL_DEV
  - PUBLIC_HOST
  - PUBLIC_HOST_DEV
